[package]
name = "no-listing-45-rand-invalid-array-access/"
version = "0.1.0"
authors = ["nobody <att@att.dot>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
