[book]
title = "The Rust Programming Language"
author = "The Rust Project Developers"
src = "src/de/src/"  # Select language to build                                             

[build]
build-dir = "book-de"
create-missing = false

[output.html]
additional-css = ["src/theme/first-edition.css"]

